---
- name: Configure db
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

- name: Configure application
  hosts: app
  become: true
  tags: app-tag
  vars:
   db_host: 10.164.0.3
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser
      notify: reload puma
      
    - name: enable puma
      systemd: name=puma enabled=yes

- name: deploy app
  hosts: app
  become: true
  tags: deploy-tag
  vars:
   db_host: 10.164.0.3
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
      notify: reload puma

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted
  
  - name: restart mongod
    service: name=mongod state=restarted
